package com.digihealth.anesthesia.interfaceParameters.yxrm.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2018-04-11T09:25:10.716+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "OperationHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OperationHttpPost {

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "UpdateState")
    public java.lang.String updateState(
        @WebParam(partName = "strRequest", name = "strRequest", targetNamespace = "http://tempuri.org/")
        java.lang.String strRequest
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "CreateOperationNotice")
    public java.lang.String createOperationNotice(
        @WebParam(partName = "strRequest", name = "strRequest", targetNamespace = "http://tempuri.org/")
        java.lang.String strRequest
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "UpdateOAState")
    public java.lang.String updateOAState(
        @WebParam(partName = "strRequest", name = "strRequest", targetNamespace = "http://tempuri.org/")
        java.lang.String strRequest
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "UpdateOperationNotice")
    public java.lang.String updateOperationNotice(
        @WebParam(partName = "strRequest", name = "strRequest", targetNamespace = "http://tempuri.org/")
        java.lang.String strRequest
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "A01")
    public java.lang.String a01();

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GetKeyCode")
    public java.lang.String getKeyCode(
        @WebParam(partName = "Sn", name = "Sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "RegCode", name = "RegCode", targetNamespace = "http://tempuri.org/")
        java.lang.String regCode,
        @WebParam(partName = "RegDate", name = "RegDate", targetNamespace = "http://tempuri.org/")
        java.lang.String regDate
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "UpdateScheduling")
    public java.lang.String updateScheduling(
        @WebParam(partName = "strRequest", name = "strRequest", targetNamespace = "http://tempuri.org/")
        java.lang.String strRequest
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GetRegCode")
    public java.lang.String getRegCode();
}
