package com.digihealth.anesthesia.interfaceParameters.yxrm.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2018-04-11T09:25:10.725+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "OperationSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface OperationSoap {

    @WebResult(name = "UpdateStateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateState", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateState")
    @WebMethod(operationName = "UpdateState", action = "http://tempuri.org/UpdateState")
    @ResponseWrapper(localName = "UpdateStateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateStateResponse")
    public java.lang.String updateState(
        @WebParam(name = "strRequest", targetNamespace = "http://tempuri.org/")
        java.lang.String strRequest
    );

    @WebResult(name = "CreateOperationNoticeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateOperationNotice", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateOperationNotice")
    @WebMethod(operationName = "CreateOperationNotice", action = "http://tempuri.org/CreateOperationNotice")
    @ResponseWrapper(localName = "CreateOperationNoticeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateOperationNoticeResponse")
    public java.lang.String createOperationNotice(
        @WebParam(name = "strRequest", targetNamespace = "http://tempuri.org/")
        java.lang.String strRequest
    );

    @WebResult(name = "UpdateOAStateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateOAState", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateOAState")
    @WebMethod(operationName = "UpdateOAState", action = "http://tempuri.org/UpdateOAState")
    @ResponseWrapper(localName = "UpdateOAStateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateOAStateResponse")
    public java.lang.String updateOAState(
        @WebParam(name = "strRequest", targetNamespace = "http://tempuri.org/")
        java.lang.String strRequest
    );

    @WebResult(name = "UpdateOperationNoticeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateOperationNotice", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateOperationNotice")
    @WebMethod(operationName = "UpdateOperationNotice", action = "http://tempuri.org/UpdateOperationNotice")
    @ResponseWrapper(localName = "UpdateOperationNoticeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateOperationNoticeResponse")
    public java.lang.String updateOperationNotice(
        @WebParam(name = "strRequest", targetNamespace = "http://tempuri.org/")
        java.lang.String strRequest
    );

    @WebResult(name = "A01Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "A01", targetNamespace = "http://tempuri.org/", className = "org.tempuri.A01")
    @WebMethod(operationName = "A01", action = "http://tempuri.org/A01")
    @ResponseWrapper(localName = "A01Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.A01Response")
    public java.lang.String a01();

    @WebResult(name = "GetKeyCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetKeyCode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetKeyCode")
    @WebMethod(operationName = "GetKeyCode", action = "http://tempuri.org/GetKeyCode")
    @ResponseWrapper(localName = "GetKeyCodeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetKeyCodeResponse")
    public java.lang.String getKeyCode(
        @WebParam(name = "Sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "RegCode", targetNamespace = "http://tempuri.org/")
        java.lang.String regCode,
        @WebParam(name = "RegDate", targetNamespace = "http://tempuri.org/")
        java.lang.String regDate
    );

    @WebResult(name = "UpdateSchedulingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateScheduling", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateScheduling")
    @WebMethod(operationName = "UpdateScheduling", action = "http://tempuri.org/UpdateScheduling")
    @ResponseWrapper(localName = "UpdateSchedulingResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateSchedulingResponse")
    public java.lang.String updateScheduling(
        @WebParam(name = "strRequest", targetNamespace = "http://tempuri.org/")
        java.lang.String strRequest
    );

    @WebResult(name = "GetRegCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRegCode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegCode")
    @WebMethod(operationName = "GetRegCode", action = "http://tempuri.org/GetRegCode")
    @ResponseWrapper(localName = "GetRegCodeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegCodeResponse")
    public java.lang.String getRegCode();
}
