package com.digihealth.anesthesia.interfaceParameters.syzxyy.cn.com.winning;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2018-03-27T16:20:17.073+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://www.winning.com.cn/", name = "WebInterfaceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebInterfaceSoap {

    @WebMethod(operationName = "HelloWorld", action = "http://www.winning.com.cn/HelloWorld")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.HelloWorldResponse")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://www.winning.com.cn/")
    public java.lang.String helloWorld();

    @WebMethod(operationName = "SendEmr", action = "http://www.winning.com.cn/SendEmr")
    @RequestWrapper(localName = "SendEmr", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.SendEmr")
    @ResponseWrapper(localName = "SendEmrResponse", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.SendEmrResponse")
    @WebResult(name = "SendEmrResult", targetNamespace = "http://www.winning.com.cn/")
    public java.lang.String sendEmr(
        @WebParam(name = "msgCode", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String msgCode,
        @WebParam(name = "sendXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String sendXml
    );
}
