package com.digihealth.anesthesia.interfaceParameters.syzxyy.cn.com.winning;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2018-03-27T16:20:17.157+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://www.winning.com.cn/", name = "WebInterfaceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WebInterfaceHttpPost {

    @WebMethod(operationName = "HelloWorld")
    @WebResult(name = "string", targetNamespace = "http://www.winning.com.cn/", partName = "Body")
    public java.lang.String helloWorld();

    @WebMethod(operationName = "SendEmr")
    @WebResult(name = "string", targetNamespace = "http://www.winning.com.cn/", partName = "Body")
    public java.lang.String sendEmr(
        @WebParam(partName = "msgCode", name = "msgCode", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String msgCode,
        @WebParam(partName = "sendXml", name = "sendXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String sendXml
    );
}
