package com.digihealth.anesthesia.interfaceParameters.qnzzy.zlsoft;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-03-30T15:46:46.279+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "ZLSoft", name = "clsIntegrationPlatfromHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ClsIntegrationPlatfromHttpPost {

    @WebResult(name = "string", targetNamespace = "ZLSoft", partName = "Body")
    @WebMethod(operationName = "IntegrationPlatfrom")
    public java.lang.String integrationPlatfrom(
        @WebParam(partName = "strXml", name = "strXml", targetNamespace = "ZLSoft")
        java.lang.String strXml
    );
}
