package com.digihealth.anesthesia.interfaceParameters.qnzzy.zlsoft;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-03-30T15:46:46.290+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "ZLSoft", name = "clsIntegrationPlatfromSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ClsIntegrationPlatfromSoap {

    @WebResult(name = "IntegrationPlatfromResult", targetNamespace = "ZLSoft")
    @RequestWrapper(localName = "IntegrationPlatfrom", targetNamespace = "ZLSoft", className = "zlsoft.IntegrationPlatfrom")
    @WebMethod(operationName = "IntegrationPlatfrom", action = "ZLSoft/IntegrationPlatfrom")
    @ResponseWrapper(localName = "IntegrationPlatfromResponse", targetNamespace = "ZLSoft", className = "zlsoft.IntegrationPlatfromResponse")
    public java.lang.String integrationPlatfrom(
        @WebParam(name = "strXml", targetNamespace = "ZLSoft")
        java.lang.String strXml
    );
}
