
package com.digihealth.anesthesia.interfaceParameters.qnzzy.zlsoft;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-03-30T15:46:46.192+08:00
 * Generated source version: 3.1.4
 * 
 */
public final class ClsIntegrationPlatfromHttpGet_ClsIntegrationPlatfromHttpGet_Client {

    private static final QName SERVICE_NAME = new QName("ZLSoft", "clsIntegrationPlatfrom");

    private ClsIntegrationPlatfromHttpGet_ClsIntegrationPlatfromHttpGet_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ClsIntegrationPlatfrom.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ClsIntegrationPlatfrom ss = new ClsIntegrationPlatfrom(wsdlURL, SERVICE_NAME);
        ClsIntegrationPlatfromHttpGet port = ss.getClsIntegrationPlatfromHttpGet();  
        
        {
        System.out.println("Invoking integrationPlatfrom...");
        java.lang.String _integrationPlatfrom_strXml = "";
        java.lang.String _integrationPlatfrom__return = port.integrationPlatfrom(_integrationPlatfrom_strXml);
        System.out.println("integrationPlatfrom.result=" + _integrationPlatfrom__return);


        }

        System.exit(0);
    }

}
