
package com.digihealth.anesthesia.interfaceParameters.qnzzy.zlsoft;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-03-30T15:46:46.324+08:00
 * Generated source version: 3.1.4
 * 
 */
 
public class ClsIntegrationPlatfromSoap_ClsIntegrationPlatfromSoap12_Server{

    protected ClsIntegrationPlatfromSoap_ClsIntegrationPlatfromSoap12_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ClsIntegrationPlatfromSoap12Impl();
        String address = "http://192.128.0.120:8087/IntegrationPlatfrom.asmx";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ClsIntegrationPlatfromSoap_ClsIntegrationPlatfromSoap12_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
