
package com.digihealth.anesthesia.interfaceParameters.qnzzy.zlsoft;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-03-30T15:46:46.312+08:00
 * Generated source version: 3.1.4
 * 
 */
 
public class ClsIntegrationPlatfromHttpPost_ClsIntegrationPlatfromHttpPost_Server{

    protected ClsIntegrationPlatfromHttpPost_ClsIntegrationPlatfromHttpPost_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ClsIntegrationPlatfromHttpPostImpl();
        String address = "CHANGE_ME";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ClsIntegrationPlatfromHttpPost_ClsIntegrationPlatfromHttpPost_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
